### ISSUE TITLE
hi, Open a separate terminal and start the scraping Tips at this step Please enter your phone (or bot token): 

### ISSUE THREAD

**Issue by cnstephen** [baileyseely1/solscan#2]
/simulation# python3 simulation.py
Please enter your phone (or bot token): 
What should be filled in here?

**Comment by baileyseely1** [comment]
hi, I never expected anyone to actually use this lol it's pretty spaghetti and my first time using python but I have a repo called "simulation" with the python code. you need to create a telegram bot 
<img width="793" alt="Screenshot 2024-05-26 at 3 19 15 AM" src="https://github.com/baileyseely1/solscan/assets/65569673/99a74310-1199-4f21-8810-3697701ab242">
and use your API key / id / token from here if I recall correctly. Sorry it's been quite a while.
https://core.telegram.org/api/obtaining_api_id
https://core.telegram.org/bots/tutorial

**Comment by cnstephen** [comment]
haha,I'm new to sol, and I found you here. It's very fateful.
I feel like this is a good program, although I haven't used it yet. Hope to continue updating! Thank you, brother
It’s really torture for people who don’t understand English
from translate google,

**Comment by cnstephen** [comment]
https://core.telegram.org/api/obtaining_api_id
It’s so difficult to apply. My enter key and left mouse button are almost broken.

**Comment by baileyseely1** [comment]
> https://core.telegram.org/api/obtaining_api_id It’s so difficult to apply. My enter key and left mouse button are almost broken.

ok brother, I will try to fix for you in a few days when I am back home. I am currently on a trip in Thailand haha. https://t.me/solanascanner -> the application is just putting all new posts from this telegram into a frontend with react, so you can just use this telegram if you want to see the new deployments. 

好的，兄弟，过几天我回家后会试着帮你修好。我目前正在泰国旅行哈哈。https://t.me/solanascanner -> 该应用程序只是将此电报中的所有新帖子都放入带有 react 的前端，因此如果您想查看 solana 区块链上的新部署，您可以使用此电报。

google translate haha

**Comment by cnstephen** [comment]
Wow, you got up so early. give you thumbs up
It was also specially translated into Chinese, so touching.
Have fun and enjoy the moment

**Comment by cnstephen** [comment]
It has been a day since I registered, but an error window still pops up. Is there something wrong with my VPN IP?
Can it be used without this condition?

**Comment by baileyseely1** [comment]
What did you register for? If you are just looking for the new deployments you can use the telegram link I sent and that channel will have everything that my website has, just in a different format. All I had done was take the information from that telegram channel and convert it to a .JSON and then display it with REACT in the frontend.

你注册是为了什么？如果您只是在寻找新的部署，您可以使用我发送的电报链接，该频道将包含我网站上的所有内容，只是格式不同。我所做的就是从该电报频道获取信息并将其转换为 .JSON，然后在前端使用 REACT 显示它。

**Comment by baileyseely1** [comment]
我实际上并没有直接访问该项目的区块链，它只是从访问 solana 区块链的电报频道中抓取

I didn't actually access the blockchain directly for this project, it is just scraping from a telegram channel that accessed the solana blockchain

**Comment by cnstephen** [comment]
I want to make appropriate modifications to the captured json, and finally do some data filtering.

**Comment by cnstephen** [comment]
Yours may not work for me as I may need to access other websites via the modified json data and then integrate it into my data. Love to toss

**Comment by baileyseely1** [comment]
okay just wait 2 days and when I am home I will try to make a solution for you brother

好吧，等两天，等我回家后，我会尽力为你找到解决方案，兄弟

**Comment by cnstephen** [comment]
Already solved
Brother is so nice
thank you so much

**Comment by cnstephen** [comment]
You travel well,have a nice day

**Comment by cnstephen** [comment]
I use a robot to forward solanascanner's message. How can I make it exactly the same as the message in the @solanascanner group? I am a novice and can only send text messages, but the effect is different from what is shown on the official website. I don't know how to do it. If you have time, please help me modify it.

**Comment by baileyseely1** [comment]
can you show me a preview of what is currently happening? can you leave a discord or whatsapp contact? :)

**Comment by cnstephen** [comment]
+8615297811135
